import {
  ColStoreInfo,
  ColKpiTargetEst,
  ColManagerItem,
  ColCrewUopItem,
  ColCrewUzItem,
  ColOtherItem
} from '../types/colTypes';

export const DEFAULT_COL_STORE_INFO: ColStoreInfo = {
  storeCode: '108120',
  storeName: 'SBX Warszawa Janki',
  month: 'WRZESIEŃ',
  year: 2025,
  openDays: 30,
  fullContractHours: 176
};

export const DEFAULT_COL_KPIS: ColKpiTargetEst = {
  salesTarget: 310000,
  salesEst: 280000,
  salesAop: 0,
  trxTarget: 10900,
  trxEst: 9700,
  trxAop: 0,
  avgDailyOpeningHours: 14,
  nonCoverageHolidayTarget: 18,
  nonCoverageHolidayEst: 18,
  nonCoverageSickTarget: 0,
  nonCoverageSickEst: 4,
  nonCoverageTrainingTarget: 75,
  matrixPlan: 'Plan A',
  tplhTarget: 6.6,
  whatIfTplhImprovement: 7.0
};

export const DEFAULT_COL_MANAGERS: ColManagerItem[] = [
  {
    id: 'mgr-1',
    name: 'Dawid Szeluga',
    position: 'SM',
    contractRatio: 1,
    baseSalary: 7200,
    planWorkHours: 176,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 176,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0,
    storeCostRatio: 1
  },
  {
    id: 'mgr-2',
    name: 'Dawid Apel',
    position: 'ASM',
    contractRatio: 1,
    baseSalary: 6300,
    planWorkHours: 176,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 176,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0,
    storeCostRatio: 1
  },
  {
    id: 'mgr-3',
    name: 'Zuzanna Makowska',
    position: 'SSV-PM',
    contractRatio: 0.75,
    baseSalary: 3510,
    planWorkHours: 96,
    planSickHours: 0,
    planHolidayHours: 5,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 96,
    estSickHours: 0,
    estHolidayHours: 5,
    estBonus: 0,
    storeCostRatio: 1
  },
  {
    id: 'mgr-4',
    name: 'Weronika Bieńkowska',
    position: 'SSV',
    contractRatio: 0.5,
    baseSalary: 5600,
    planWorkHours: 88,
    planSickHours: 0,
    planHolidayHours: 3,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 39,
    estSickHours: 4,
    estHolidayHours: 3,
    estBonus: 0,
    storeCostRatio: 1
  },
  {
    id: 'mgr-5',
    name: 'Nikola Studzińska',
    position: 'SSV',
    contractRatio: 0.5,
    baseSalary: 2300,
    planWorkHours: 56,
    planSickHours: 0,
    planHolidayHours: 4,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 60,
    estSickHours: 0,
    estHolidayHours: 4,
    estBonus: 0,
    storeCostRatio: 1
  },
  {
    id: 'mgr-6',
    name: 'Kamil Kamiński',
    position: 'SSV',
    contractRatio: 1,
    baseSalary: 5600,
    planWorkHours: 128,
    planSickHours: 0,
    planHolidayHours: 6,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 128,
    estSickHours: 0,
    estHolidayHours: 6,
    estBonus: 300,
    storeCostRatio: 1
  },
  // Special rows
  {
    id: 'mgr-maternity',
    name: 'Manager Maternity',
    position: 'Manager Maternity',
    contractRatio: 0,
    baseSalary: 0,
    planWorkHours: 0,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 0,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0,
    storeCostRatio: 1,
    isSpecialRow: true
  },
  {
    id: 'mgr-bench',
    name: 'Manager Bench',
    position: 'Manager Bench',
    contractRatio: 0,
    baseSalary: 0,
    planWorkHours: 0,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 0,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0,
    storeCostRatio: 1,
    isSpecialRow: true
  },
  {
    id: 'mgr-dm',
    name: 'DM costs',
    position: 'DM costs',
    contractRatio: 0,
    baseSalary: 0,
    planWorkHours: 0,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 685,
    isDisability: false,
    estWorkHours: 0,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 685,
    storeCostRatio: 1,
    isSpecialRow: true
  },
  {
    id: 'mgr-dos',
    name: 'DOS+ accrual',
    position: 'DOS+ accrual',
    contractRatio: 0,
    baseSalary: 0,
    planWorkHours: 0,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 0,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0,
    storeCostRatio: 1,
    isSpecialRow: true
  },
  {
    id: 'mgr-holiday-accrual',
    name: 'Holiday accrual',
    position: 'Holiday accrual',
    contractRatio: 0,
    baseSalary: 3454, // z Rezerwy urlopowej G106
    planWorkHours: 0,
    planSickHours: 0,
    planHolidayHours: 0,
    planBonus: 0,
    isDisability: false,
    estWorkHours: 0,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 1819,
    storeCostRatio: 1,
    isSpecialRow: true
  }
];

export const DEFAULT_COL_CREW_UOP: ColCrewUopItem[] = [
  {
    id: 'uop-1',
    name: 'Hanna Domachowska',
    position: 'BT',
    contractRatio: 0.5,
    hourlyRate: 31.4,
    planWorkHours: 88,
    planSickHours: 0,
    planHolidayHours: 0,
    isDisability: false,
    estWorkHours: 85,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0
  },
  {
    id: 'uop-2',
    name: 'Gabriela Znojek',
    position: 'B',
    contractRatio: 0.75,
    hourlyRate: 30.75,
    planWorkHours: 132,
    planSickHours: 0,
    planHolidayHours: 0,
    isDisability: false,
    estWorkHours: 120,
    estSickHours: 0,
    estHolidayHours: 0,
    estBonus: 0
  }
];

export const DEFAULT_COL_CREW_UZ: ColCrewUzItem[] = [
  { id: 'uz-1', name: 'Wiktoria Lenart', position: 'BT', hourlyRate: 31.4, planWorkHours: 30, estWorkHours: 45, bonus: 50 },
  { id: 'uz-2', name: 'Wiktoria Walczak', position: 'BT', hourlyRate: 31.4, planWorkHours: 30, estWorkHours: 47.5, bonus: 0 },
  { id: 'uz-3', name: 'Marysia Szulczyk', position: 'BT', hourlyRate: 31.4, planWorkHours: 50, estWorkHours: 30.5, bonus: 0 },
  { id: 'uz-4', name: 'Zuzanna Dworak', position: 'B', hourlyRate: 30.4, planWorkHours: 30, estWorkHours: 39.5, bonus: 0 },
  { id: 'uz-5', name: 'Aleksandra Płużycka', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 56, bonus: 0 },
  { id: 'uz-6', name: 'Maja Piasecka', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 67, bonus: 0 },
  { id: 'uz-7', name: 'Julia Zimnicka', position: 'B', hourlyRate: 30.5, planWorkHours: 50, estWorkHours: 51, bonus: 150 },
  { id: 'uz-8', name: 'Julia Gnieciak', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 0, bonus: 0 },
  { id: 'uz-9', name: 'Magdalena Wiśniewska', position: 'B', hourlyRate: 30.5, planWorkHours: 50, estWorkHours: 46, bonus: 0 },
  { id: 'uz-10', name: 'Zuzanna Gzula', position: 'B', hourlyRate: 30.5, planWorkHours: 50, estWorkHours: 45, bonus: 0 },
  { id: 'uz-11', name: 'Gabriela Suwald', position: 'B', hourlyRate: 30.5, planWorkHours: 50, estWorkHours: 44, bonus: 0 },
  { id: 'uz-12', name: 'Agnieszka Charmuszko', position: 'B', hourlyRate: 30.5, planWorkHours: 50, estWorkHours: 33, bonus: 0 },
  { id: 'uz-13', name: 'Julia Szulc', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 109, bonus: 200 },
  { id: 'uz-14', name: 'Katarzyna Magryta', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 0, bonus: 0 },
  { id: 'uz-15', name: 'Emilia Ebert', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 87.5, bonus: 0 },
  { id: 'uz-16', name: 'Uczeń', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 0, bonus: 0 },
  { id: 'uz-17', name: 'Aleksandra Kurowska', position: 'B', hourlyRate: 30.5, planWorkHours: 50, estWorkHours: 30.5, bonus: 0 },
  { id: 'uz-18', name: 'Małgorzata Kręt', position: 'B', hourlyRate: 30.5, planWorkHours: 30, estWorkHours: 43, bonus: 0 },
  { id: 'uz-19', name: 'Anna Rutkowska', position: 'B', hourlyRate: 30.5, planWorkHours: 70, estWorkHours: 59, bonus: 0 },
  { id: 'uz-20', name: 'Agata Boruc', position: 'B', hourlyRate: 30.5, planWorkHours: 70, estWorkHours: 0, bonus: 0 }
];

export const DEFAULT_COL_OTHER_COSTS: ColOtherItem[] = [
  { id: 'oth-1', label: 'Medical examination ryczałt', planVal: 150, estVal: 150 },
  { id: 'oth-2', label: 'Bonus "Recommend a friend" (netto)', planVal: 0, estVal: 0 },
  { id: 'oth-3', label: 'Bonus SSV No Area', planVal: 300, estVal: 300, ratePct: 0.001 },
  { id: 'oth-4', label: 'Bonus CREW', planVal: 600, estVal: 400, ratePct: 0.002 },
  { id: 'oth-5', label: 'Wyksięgowanie PFRON Manager', planVal: 0, estVal: 0 },
  { id: 'oth-6', label: 'Wyksięgowanie PFRON Crew', planVal: 0, estVal: 0 },
  { id: 'oth-7', label: 'ADP', planVal: 600, estVal: 600 },
  { id: 'oth-8', label: 'Other (Koszty HR, corrections from previous month etc.)', planVal: 0, estVal: 0 },
  { id: 'oth-9', label: 'PPK', planVal: 250, estVal: 250, extraMeta: { ppkMgr: 250, ppkCrew: 0 } },
  { id: 'oth-10', label: 'Drivers', planVal: 220, estVal: 206, extraMeta: { costPerDrop: 14 } }
];
